- name: Set up MongoDB 6.0 on Ubuntu 22.04
  hosts: localhost
  connection: local
  become: yes
  vars:
    mongo_version: "6.0"
    mongo_repo_url: "https://repo.mongodb.org/apt/ubuntu"
    mongo_distribution: "jammy"
    mongo_component: "multiverse"
    mongo_key_url: "https://www.mongodb.org/static/pgp/server-6.0.asc"
    mongo_keyring: "/usr/share/keyrings/mongodb-archive-keyring.gpg"
    mongo_conf_file: "/etc/mongod.conf"
    database_name: "mydatabase"
    mongodb_root_user: "admin"
    mongodb_root_password: "smartes"
    mongodb_admin_user: "dbuser"
    mongodb_admin_password: "dbpassword"

  tasks:
    - name: Add MongoDB GPG key
      ansible.builtin.shell: |
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -

    - name: Add MongoDB APT repository
      ansible.builtin.shell: |
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade all APT packages
      apt:
        upgrade: dist

    - name: Install MongoDB
      ansible.builtin.apt:
        name:
          - mongodb-org
        state: present

    - name: Ensure MongoDB service is enabled
      ansible.builtin.systemd:
        name: mongod
        enabled: yes

    - name: Start MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started

    - name: Check MongoDB service status
      ansible.builtin.service_facts:

    - name: Modify MongoDB configuration file
      ansible.builtin.blockinfile:
        path: "{{ mongo_conf_file }}"
        block: |
          security:
            authorization: enabled
        create: yes

    - name: Allow MongoDB port through firewall
      ansible.builtin.ufw:
        rule: allow
        port: 27017

    - name: Restart MongoDB service to apply changes
      ansible.builtin.systemd:
        name: mongod
        state: restarted

    - name: Check MongoDB service status
      systemd:
        name: mongod  # MongoDB service name might vary; adjust as needed
        state: started
      register: mongodb_status

    - name: Print MongoDB service status
      debug:
        msg: "MongoDB service status is {{ mongodb_status }}"
    
    - name: Create MongoDB root user
      mongodb_user:
        login_port: "27017"
        database: "admin"
        name: "{{ mongodb_root_user }}"
        password: "{{ mongodb_root_password }}"
        roles: "root"

    - name: Create MongoDB administrative user siteUserAdmin
      mongodb_user:
        login_user: "{{ mongodb_root_user }}"
        login_password: "{{ mongodb_root_password }}"
        login_port: "27017"
        database: "{{ database_name }}"
        name: "{{ mongodb_admin_user }}"
        password: "{{ mongodb_admin_password }}"
        roles:
          - { db: "admin", role: "readWrite" }
          - { db: "{{ database_name }}", role: "readWrite" }


