---
- name: Set up MongoDB 6.0 on Ubuntu 22.04
  hosts: localhost
  connection: local
  become: yes
  vars:
    mongo_version: "6.0"
    mongo_repo_url: "https://repo.mongodb.org/apt/ubuntu"
    mongo_distribution: "jammy"
    mongo_component: "multiverse"
    mongo_key_url: "https://www.mongodb.org/static/pgp/server-6.0.asc"
    mongo_keyring: "/usr/share/keyrings/mongodb-archive-keyring.gpg"
    mongo_conf_file: "/etc/mongod.conf"

  tasks:
    - name: Install required dependencies
      ansible.builtin.apt:
        name: gnupg
        state: present
        update_cache: yes

    - name: Remove existing MongoDB APT sources list file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/mongodb-org-6.0.list
        state: absent

    - name: Clean APT cache
      ansible.builtin.apt:
        update_cache: yes
        autoclean: yes

    - name: Add MongoDB GPG key
      ansible.builtin.apt_key:
        url: "{{ mongo_key_url }}"
        state: present
        keyring: "{{ mongo_keyring }}"

    - name: Add MongoDB APT repository
      ansible.builtin.apt_repository:
        repo: "deb [ arch=amd64,arm64 signed-by={{ mongo_keyring }} ] {{ mongo_repo_url }} {{ mongo_distribution }}/mongodb-org/{{ mongo_version }} {{ mongo_component }}"
        state: present
        filename: "mongodb-org-{{ mongo_version }}.list"

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all APT packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present

    - name: Ensure MongoDB service is enabled
      ansible.builtin.systemd:
        name: mongod
        enabled: yes

    - name: Start MongoDB service
      ansible.builtin.systemd:
        name: mongod
        state: started

    - name: Modify MongoDB configuration file
      ansible.builtin.blockinfile:
        path: "{{ mongo_conf_file }}"
        block: |
          security:
            authorization: enabled
          net:
            port: 27017
            bindIp: 127.0.0.1
        create: yes

    - name: Allow MongoDB port through firewall
      ansible.builtin.ufw:
        rule: allow
        port: 27017

    - name: Restart MongoDB service to apply changes
      ansible.builtin.systemd:
        name: mongod
        state: restarted

