name: Build AMI with Packer and Ansible

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out your repository to the runner

      - name: Print Current Directory
        run: pwd  # Prints the current directory

      - name: List Files in Current Directory
        run: ls -l  # Lists files in the current directory

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust to a Python version available in your environment

      - name: Install Ansible and Dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible
          sudo /opt/pipx/venvs/ansible-core/bin/python -m pip install psycopg2-binary  # Install psycopg2-binary if needed
          
      - name: Install Latest Packer and Initialize
        run: |
          wget -O packer.zip https://releases.hashicorp.com/packer/1.11.1/packer_1.11.1_linux_amd64.zip
          unzip -o packer.zip -d packer_install
          sudo mv packer_install/packer /usr/local/bin/
          rm -rf packer.zip packer_install  # Clean up extracted files and zip
          packer --version  # Verify Packer installation
          packer init packer/mongodb.pkr.hcl  # Initialize Packer configuration

      - name: Validate Packer Template
        run: |
          cd packer
          packer validate packer/mongodb.pkr.hcl

      - name: Run Packer build and print AMI ID
        id: packer-build
        run: |
          packer build -machine-readable \
            -var aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            packer/mongodb.pkr.hcl | tee packer_output.txt
          echo "AMI_ID=$(awk -F, '$0 ~/artifact,0,id/ {print $6}' packer_output.txt)" >> $GITHUB_ENV
          echo "AMI_ID=$(awk -F, '$0 ~/artifact,0,id/ {print $6}' packer_output.txt)"  # Print AMI ID to console

      - name: Save AMI_ID as artifact
        uses: actions/upload-artifact@v2
        with:
          name: packer-output
          path: packer_output.txt
