name: Build AMI with Packer and Ansible

on:
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Current Directory
        run: pwd

      - name: List Files in Current Directory
        run: ls -l

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Ansible and Dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible
          sudo /opt/pipx/venvs/ansible-core/bin/python -m pip install psycopg2-binary

      - name: Install Pymongo and python3 PIP
        run: |
          sudo apt-get install -y python3-pip
          pip3 install ansible pymongo

      - name: Install Latest Packer and Initialize
        run: |
          wget -O packer.zip https://releases.hashicorp.com/packer/1.11.1/packer_1.11.1_linux_amd64.zip
          unzip -o packer.zip -d packer_install
          sudo mv packer_install/packer /usr/local/bin/
          rm -rf packer.zip packer_install
          packer --version
          packer init packer/mongodb.pkr.hcl

      - name: Validate Packer Template
        run: |
          cd packer
          packer validate mongodb.pkr.hcl

      - name: Run Packer build and print AMI ID
        id: packer-build
        run: |
          cd packer
          packer build -machine-readable \
            -var aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            mongodb.pkr.hcl | tee packer_output.txt
          AMI_ID=$(awk -F, '$0 ~/artifact,0,id/ {print $6}' packer_output.txt)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

      - name: Save AMI_ID as artifact
        uses: actions/upload-artifact@v2
        with:
          name: packer-output
          path: ./
          if-no-files-found: error
