name: Build AMI with Packer and Ansible

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          
      - name: Install psycopg2-binary
        run: |
          sudo /opt/pipx/venvs/ansible-core/bin/python -m pip install psycopg2-binary

      - name: Install Latest Packer and Initialize
        run: |
          wget -O packer.zip https://releases.hashicorp.com/packer/1.11.1/packer_1.11.1_linux_amd64.zip
          unzip -o packer.zip -d packer_install
          sudo mv packer_install/packer /usr/local/bin/
          rm -rf packer.zip packer_install  # Clean up extracted files and zip
          packer --version  # Verify Packer installation
          packer init main/packer/mongodb.pkr.hcl

      - name: Validate Packer Template
        run: packer validate main/packer/mongodb.pkr.hcl

      - name: Run Packer build and print AMI ID
        run: |
          packer build -machine-readable -var aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }} -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} /home/runner/work/devops_final_project/devops_final_project/main/packer/mongodb.pkr.hcl | tee packer_output.txt
          ami_id=$(awk -F, '$0 ~/artifact,0,id/ {print $6}' packer_output.txt)
          echo "AMI_ID=$ami_id" >> $GITHUB_ENV
          echo "AMI_ID=$ami_id"  # Print AMI ID to console

      - name: Save AMI_ID as artifact
        uses: actions/upload-artifact@v2
        with:
          name: packer-output
          path: packer_output.txt
