name: Deploy infra with terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download AMI ID Artifact
        uses: actions/download-artifact@v3
        with:
          name: packer_output
          path: ./

      - name: Extract AMI ID
        id: ami-id
        run: |
          AMI_ID=$(cat ./artifact/packer_output.txt)
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Adjust this to your required Terraform version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}
          aws-region: "us-east-1" 

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var "ami_id=${{ env.AMI_ID }}"

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -var "ami_id=${{ env.AMI_ID }}"
