name: Download and Use Variable

on:
  workflow_dispatch:

jobs:
  use-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: test-variable
          path: ./artifact

      - name: Read variable from file
        id: read-variable
        run: |
          TEST_VARIABLE=$(cat ./artifact/test_variable.txt | cut -d '=' -f2)
          echo "TEST_VARIABLE=$TEST_VARIABLE" >> $GITHUB_ENV

      - name: Use the variable
        run: echo "The variable is ${{ env.TEST_VARIABLE }}"
