name: Create and Save Variable

on:
  workflow_dispatch:

jobs:
  create-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Variable
        run: echo "HelloWorld" > test_variable.txt
    
      - name: List Files
        run: ls -al  # Optional: List files to verify 'test_variable.txt' is created

      - name: Upload Variable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-variable
          path: ./artifact
