name: Set Variable and Save as Environment Variable

on:
  workflow_dispatch:

jobs:
  set-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variable
        run: echo "TEST_VARIABLE=HelloWorld" > test_variable.txt

      - name: Display variable value
        run: |
          TEST_VARIABLE=$(cat test_variable.txt | cut -d '=' -f2)
          echo "Plain text: $TEST_VARIABLE"  # Print for verification in logs

      - name: Set environment variable
        run: echo "TEST_VARIABLE=$TEST_VARIABLE" >> $GITHUB_ENV

      - name: Display saved environment variable
        run: echo "Save TEST_VARIABLE: $TEST_VARIABLE"

      - name: Use saved environment variable
        run: echo "Using TEST_VARIABLE: $TEST_VARIABLE"
