name: Set Variable and Upload

on:
  workflow_dispatch:

jobs:
  set-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set and save variable
        run: echo "TEST_VARIABLE=HelloWorld" > test_variable.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-variable
          path: test_variable.txt
