name: Set Variable and Save Secret

on:
  workflow_dispatch:

jobs:
  set-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variable
        run: echo "TEST_VARIABLE=HelloWorld" > test_variable.txt

      - name: Get public key for encryption
        id: get-key
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
        run: |
          response=$(curl -s -H "Authorization: token $GH_PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          echo "PUBLIC_KEY=$(echo $response | jq -r .key)" >> $GITHUB_ENV
          echo "KEY_ID=$(echo $response | jq -r .key_id)" >> $GITHUB_ENV

      - name: Encrypt the secret value
        env:
          PUBLIC_KEY: ${{ env.PUBLIC_KEY }}
        run: |
          TEST_VARIABLE=$(cat test_variable.txt | cut -d '=' -f2)
          echo "ENCRYPTED_VALUE=$(echo -n $TEST_VARIABLE | openssl rsautl -encrypt -pubin -inkey <(echo $PUBLIC_KEY | base64 -d) | base64 -w 0)" >> $GITHUB_ENV

      - name: Create GitHub repository secret
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
          ENCRYPTED_VALUE: ${{ env.ENCRYPTED_VALUE }}
          KEY_ID: ${{ env.KEY_ID }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/TEST_VARIABLE \
            -d "{\"encrypted_value\":\"${ENCRYPTED_VALUE}\",\"key_id\":\"${KEY_ID}\"}"
