name: Build AMI with Packer and Ansible

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Print Current Directory
        run: pwd  # Prints the current directory

      - name: List Files in Current Directory
        run: ls -l  # Lists files in the current directory

      - name: Checkout Repository
        uses: actions/checkout@v4  # Checks out your repository to the runner

      - name: List Files in Repository
        run: ls -l

      # Add more steps for your Packer and Ansible build process here
