name: Set Variable and Save Secret

on:
  workflow_dispatch:

jobs:
  set-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variable
        run: echo "TEST_VARIABLE=HelloWorld" > test_variable.txt

      - name: Get public key for encryption
        id: get-key
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
        run: |
          response=$(curl -s -H "Authorization: token $GH_PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          echo "::set-output name=key::$(echo $response | jq -r .key)"
          echo "::set-output name=key_id::$(echo $response | jq -r .key_id)"

      - name: Encrypt the secret value
        id: encrypt
        run: |
          TEST_VARIABLE=$(cat test_variable.txt | cut -d '=' -f2)
          echo "::set-output name=encrypted_value::$(echo -n $TEST_VARIABLE | openssl rsautl -encrypt -pubin -inkey <(echo ${{ steps.get-key.outputs.key }} | base64 -d) | base64 -w 0)"

      - name: Create GitHub repository secret
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
        run: |
          curl -X PUT \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/TEST_VARIABLE \
            -d '{"encrypted_value":"${{ steps.encrypt.outputs.encrypted_value }}","key_id":"${{ steps.get-key.outputs.key_id }}"}'
