name: Set Variable and Save Secret

on:
  workflow_dispatch:

jobs:
  set-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variable
        run: echo "TEST_VARIABLE=HelloWorld" > test_variable.txt

      - name: Create GitHub repository secret
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
        run: |
          TEST_VARIABLE=$(cat test_variable.txt | cut -d '=' -f2)
          curl -X PUT \
            -H "Authorization: token $GH_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/TEST_VARIABLE \
            -d '{"encrypted_value":"'$TEST_VARIABLE'"}'
