name: Set Variable and Encrypt

on:
  workflow_dispatch:

jobs:
  set-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variable
        run: echo "TEST_VARIABLE=HelloWorld" > test_variable.txt

      - name: Get public key for encryption
        id: get-key
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
        run: |
          response=$(curl -s -H "Authorization: token $GH_PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          echo "PUBLIC_KEY=$(echo $response | jq -r .key)" >> $GITHUB_ENV
          echo "KEY_ID=$(echo $response | jq -r .key_id)" >> $GITHUB_ENV
          echo $response

      - name: Encrypt the secret value
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}  # Ensure this secret is correctly set in your repository secrets
        run: |
          TEST_VARIABLE=$(cat test_variable.txt | cut -d '=' -f2)
          echo "Plain text: $TEST_VARIABLE"  # Print for verification in logs
          echo "Public Key: $PUBLIC_KEY"  # Print for verification in logs

          # Decode the base64-encoded public key and write to a temp file
          echo "$PUBLIC_KEY" | base64 -d > public_key.pem

          # Encrypt the plain text using openssl pkeyutl with the decoded public key
          ENCRYPTED_VALUE=$(echo -n "$TEST_VARIABLE" | openssl pkeyutl -encrypt -pubin -inkey public_key.pem | base64 -w 0)
          echo "ENCRYPTED_VALUE=$ENCRYPTED_VALUE" >> $GITHUB_ENV
          echo "Encrypted value: $ENCRYPTED_VALUE"  # Print for verification in logs

          # Clean up temp file
          rm public_key.pem
