name: Set Variable and Save Secret

on:
  workflow_dispatch:

jobs:
  set-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variable
        run: echo "TEST_VARIABLE=HelloWorld" > test_variable.txt

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token

      - name: Save variable as repository secret
        run: |
          TEST_VARIABLE=$(cat test_variable.txt | cut -d '=' -f2)
          gh secret set TEST_VARIABLE --body "$TEST_VARIABLE"
